version: "3.9"
services:
  web:
    build: /mnt/c/Users/moreno/Desktop/sprint1_equip1_sims/Grup1_Sprint1
    container_name: ezyridephp-web
    volumes:
      - /mnt/c/Users/moreno/Desktop/sprint1_equip1_sims/Grup1_Sprint1/src:/var/www/html
    ports:
      - "0.0.0.0:8080:80"
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mongopostgre
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: ezyridemongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
