services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sims_frontend
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped
